name: Unit-Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run Unit Tests
        run: make test
      - name: Test Build
        uses: bazhenov/action-avr-make@v1.0
        run: make all